name: Grace Changelog
on:
  issues:
    types: [closed,reopened]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if it has release drafter config file
        id: check_release_drafter
        run: |
          has_release_drafter=$([ -f .github/release-drafter.yml ] && echo "true" || echo "false")
          echo ::set-output name=has_release_drafter::${has_release_drafter}
      - name: Extract branch name
        id: extract_branch
        run: echo ::set-output name=value::${GITHUB_REF:11}
      # If it has release drafter:
      - uses: release-drafter/release-drafter@v5.19.0
        if: steps.check_release_drafter.outputs.has_release_drafter == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ steps.extract_branch.outputs.value }}
          filter-by-commitish: true
